#!/bin/bash

# ../serwer 15 &
# Nalezy odpalic time ./skrypt - czas wykonania powinien byc rowny podanemu na dole czasowi zakonczenia.

../klient 3 5 1 3 7 & # 1
sleep 1
../klient 3 2 2 3 4 & # 2
sleep 1
../klient 5 5 11 12 13 14 15 & # 3
sleep 4
../klient 3 6 2 9 10 # 4

# 0: 1 dostaje
# 2: 3 dostaje
# 5: 2 dostaje
# 7: 1 dostaje, 3 dostaje, 4 dostaje
# 12: 3 dostaje
# 13: 2 dostaje
# 15: 1 dostaje, 4 dostaje
# 17: 3 dostaje
# 21: 2 dostaje
# 22: 3 dostaje
# 23: 4 dostaje
# 29: koniec

