#!/bin/bash

#----------------------------------------
#
# Procedura jest nieznacznym rozwinieciem 
# poprzedniego przykladu
#
#-----------------------------------------
echo Program $0 wywolano z $# parametrami
echo -- pierwszy:   $1
echo -- drugi:      $2
echo -- trzeci:     $3
echo -- wszystkie:  $*

echo "O ile shift?  "
read i

shift $i

echo Po przesunieciu zostalo $# parametrow
echo -- pierwszy:   $1
echo -- drugi:      $2
echo -- trzeci:     $3
echo -- wszystkie:  $*

