#include <stdio.h>

#include <rpc/rpc.h>    /* standard RPC include file */
#include "sad.h"       /* this file is generated by rpcgen */

main(int argc, char *argv[])
{
    CLIENT *cl;         /* RPC handle */
    char *server;
    intpair data;
    intpair *result;      /* return value from bin_date_1() */

    if (argc < 4) {
        fprintf(stderr, "usage: %s hostname IntA IntB\n", argv[0]);
        exit(1);
    }

    server = argv[1];

    /* Client handle */
    if ((cl = clnt_create(server, SAD_PROGRAM, SAD_VERS, "tcp")) == NULL) {
         clnt_pcreateerror(server);
         exit(2);
    }

    data.a = atoi(argv[2]);
    data.b = atoi(argv[3]);
    if ( (result = sad_1(&data, cl)) == NULL) {
        clnt_perror(cl, server);
        exit(3);
    }
    printf("sum: %d, difference: %d\n", result->a, result->b);

    clnt_destroy(cl);
    exit(0);
}
