/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SAD_H_RPCGEN
#define _SAD_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct intpair {
	int a;
	int b;
};
typedef struct intpair intpair;

#define SAD_PROGRAM 0x30000000
#define SAD_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define SAD 1
extern  intpair * sad_1(intpair *, CLIENT *);
extern  intpair * sad_1_svc(intpair *, struct svc_req *);
extern int sad_program_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SAD 1
extern  intpair * sad_1();
extern  intpair * sad_1_svc();
extern int sad_program_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_intpair (XDR *, intpair*);

#else /* K&R C */
extern bool_t xdr_intpair ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SAD_H_RPCGEN */
